### ISSUE TITLE
Wrong padding for boxes with icon in print.css

### ISSUE THREAD

**Issue by LarsGit223** [selfthinker/dokuwiki_plugin_wrap#104]
Hi,

the padding for boxes with icons in print.css seems to be wrong. The text is printed over the icon when I export wrap boxes to pdf (with bookcreator, dw2pdf plugins).

The following patch fixes the issue:

``` .patch
@@ -9,7 +9,7 @@
 .dokuwiki div.wrap_danger, .dokuwiki div.wrap_warning, .dokuwiki div.wrap_caution, .dokuwiki div.wrap_notice, .dokuwiki div.wrap_safety,
 .dokuwiki div.wrap_info, .dokuwiki div.wrap_important, .dokuwiki div.wrap_alert, .dokuwiki div.wrap_tip, .dokuwiki div.wrap_help, .dokuwiki div.wrap_todo, .dokuwiki div.wrap_download {
     border: 2px solid #999;
-    padding: 1em 1em .5em;
+    padding: 1em 1em .5em 70px;
     margin-bottom: 1.5em;
 }
 .dokuwiki span.wrap_box,
```

Greetings, Lars

**Comment by selfthinker** [comment]
Well, there is no icon in the print version. I'm not sure how the PDF creating plugins work and where they get their styling from. The dw2pdf page only talks about print.css but that cannot be correct then.

**Comment by LarsGit223** [comment]
Ok, I probably now the reason.

My first attempt exporting to pdf ended up in having all boxes exported only with a border and text. No background-image, no background color. So that is the correct behaviour in print mode?

I thought it is a bug and the dw2pdf plugin allows to configure the names of plugins from which the screen.css and style.css shall be used. So I put wrap in there and was happy to see all the colors and icons in print mode also.

If I think of my own very very rudimentary CSS import functions I could assume that in this case maybe the mpdf lib included in the dw2pdf plugin does not handle the @media annotations correctly. Looks like it is using screen properties and then overwrites it with print properties. Then you get the background-color and icon from the screen.css but then the print.css overwrites the padding from screen.css.

If you say there are no backround colors and icons in print mode, then this bug can be closed.

Also I have to say that I like to have it in there in print mode also, guess I have to use a custom made css file then?

**Comment by selfthinker** [comment]
> My first attempt exporting to pdf ended up in having all boxes exported only with a border and text. No background-image, no background color. So that is the correct behaviour in print mode?

Yes, that's how it should be. However, this is due to most browsers not printing background colours or images by default. It should probably behave differently for PDFs. Maybe there should be a separate `pdf.css` for that...
