### ISSUE TITLE
Can't click on any WRAP toolbar icon

### ISSUE THREAD

**Issue by UXlibrarian** [selfthinker/dokuwiki_plugin_wrap#107]
Hello! I'm using the default template in the latest version of WRAP and Chrome. I can click on the WRAP button on the toolbar. However, all the WRAP buttons appear to have a too-low Z-index. I can see the images, but cannot click on them.

**Comment by selfthinker** [comment]
I cannot reproduce this. Could it be that another plugin is interfering?

**Comment by selfthinker** [comment]
Closing due to missing feedback.
