### ISSUE TITLE
Conflicts with Bureaucracy Plugin

### ISSUE THREAD

**Issue by UXlibrarian** [selfthinker/dokuwiki_plugin_wrap#111]
Hello! 

I'm really appreciative of your plugin. I'm using it to style the generated pages that are created when a form is submitted to my site via a Bureaucracy Plugin form. The %> are being dropped off from the WRAPs. Do you have any suggestion on how to overcome this?

**Comment by selfthinker** [comment]
Sorry, I don't understand your questions. What `%>` are you talking about? Some examples would be good.

**Comment by UXlibrarian** [comment]
Sorry! 

For example, I have it so that it says:

<WRAP column 55%>
some text here
</WRAP>

<WRAP column 45%>
More text
</WRAP>

When this is rendered using Bureaucracy plugin, the %> is drop from both opening WRAP tags.

**Comment by Klap-in** [comment]
Percentage are also used by the Bureaucracy plugin for some placeholders for dates.
See https://www.dokuwiki.org/plugin:bureaucracy#creating_templates

To preserve the  `%` character you have to write it as `%%` in the template.

**Comment by Klap-in** [comment]
Are there simple ideas for improving the user experiences with percentage characters?

**Comment by selfthinker** [comment]
Ah, okay, so this is not really an issue with the Wrap plugin but with the Bureaucracy plugin.
Although I don't think it will be "fixed" in there either as it's not a bug.
