### ISSUE TITLE
Can't display toolbar images

### ISSUE THREAD

**Issue by maie** [selfthinker/dokuwiki_plugin_wrap#114]
Hi,

My editor can't display the toolbar's images. Like this:
![wrp](https://cloud.githubusercontent.com/assets/2394381/8518261/eb5fca58-23fa-11e5-868a-a9def14ffd8f.jpg)

The source code is below:
```
<img src="http://wiki.xxx.com/lib/images/toolbar/http://wiki.xxx.com/lib/plugins/wrap/images/toolbar/column.png" alt="" width="16" height="16">
```
What should I do?
Best regard.

**Comment by selfthinker** [comment]
I just fixed this and made a new release. Please install the latest version.

**Comment by maie** [comment]
The problem is solved. Thank you very much.
