### ISSUE TITLE
class for "onlypdf"?

### ISSUE THREAD

**Issue by rwoldu** [selfthinker/dokuwiki_plugin_wrap#130]
similar to #129 

Hi,

is it possible to develop a class that allows to show text (or maybe replaces text) only when in PDFs?
E.g. as the syntax for wrap onlyprint and wrap noprint?

Thanks in advance!

(sorry if it the wrong place for requests, but I am not sure where to ask...)
BTW: great plugin, thanks!

**Comment by selfthinker** [comment]
This might be possible. The DW2PDF plugin supports `pdf.css` files and the ODT plugin supports `odt.css` files. Those could be used to create classes specifically for them.

But... both of them already use each plugin's `print.css` by default. So, you could already use `onlyprint` and `noprint` and it should work without the need of more classes.

**Comment by selfthinker** [comment]
I will close this now as what you're asking for can be achieved with 'onlyprint'. Please feel free to re-open the issue with more information if that doesn't work in your use case.
