### ISSUE TITLE
Disable emulated headers by default

### ISSUE THREAD

**Issue by Celti** [selfthinker/dokuwiki_plugin_wrap#131]
Emulated headers are not necessary anymore and get in the way of certain content (e.g., a box with an all-italicised section where parts of the italicised text are bolded for emphasis). Disabling them by default on new installations, with a config option for those who still need them or an extra class that enables them per wrap, is preferable. Failing that, a config option for them that is not disabled by default or a class that disables them per wrap would do.

**Comment by selfthinker** [comment]
I guess it makes sense to slowly retire the emulated headers. But I would enable them by default as disabling them would potentially break existing layouts. Enable or disable per wrap is probably not worth it, though.

**Comment by selfthinker** [comment]
I've implemented this now in #168 via a new config option which can enable them. The plan is to remove them completely after a while.
