### ISSUE TITLE
No problem but a suggestion: copy to clipboard per click

### ISSUE THREAD

**Issue by diltigug** [selfthinker/dokuwiki_plugin_wrap#157]
Hello,

I have no problem with teh plugin but a suggestion: 

It would be a nice feature for the download box if the graphic is a button that copies the text from the box to the clipboard.

Is that feasible? Unfortunately, I can not program.

greetings

**Comment by selfthinker** [comment]
I don't think this is something that the Wrap plugin should provide. Having such a functionality in another plugin makes more sense.
The [Clippy plugin](https://www.dokuwiki.org/plugin:clippy) does something similar. Maybe that already meets your needs?
