### ISSUE TITLE
Suggestion: alternative multicolumn option?

### ISSUE THREAD

**Issue by ggieling** [selfthinker/dokuwiki_plugin_wrap#159]
The current multi-column option (e.g. col3) in the wrap plugin (https://www.dokuwiki.org/plugin:wrap). presents its contents in 3 columns, regardless of the width of the screen which could be a too small number of columns on wide screens/small fontsizes, or a too large number of columns on small screens /large font sizes.  Try for example (http://www.won-nl.org/wontest/public/en/patinf#tab__bibliographic1) on a small device
p.s. above page works in Chrome, not in Firefox.

In one page in a testing environment I have created a custom wrap linked to a custom userstyle.css with a dependency on the media width.  In this method the number of columns is determined by the width of the screen.  Disadvantage in this method is that I have to define different stylesets for each desired column width and multiple media subdefinitions pere set.
 I'm not an expert in this type of work and have no experience at all with less, but I think it should be possible to somehow create a multicolumn option in the wrap plugin that is defined by the minimum column width included as a ariable. This should result in int(desired column-width/dokuwiki__content width) number of columns in this wrap defined div.  To make this font-size independent, both widths should be defined in Em.

Do you think this would be a useful addition to the wrap plugin?
The page that adopts in my testing site can be found here (http://www.won-nl.org/wontest/public/en/ledenbestand)

**Comment by selfthinker** [comment]
Thanks for the suggestion, that generally makes sense.
But there is a native way to do that without the need of media queries. I already have an alternative working and will add it soon.

**Comment by selfthinker** [comment]
I have just added my alternative in #165. It's not released yet, only in master.
Does that meet your needs?

**Comment by ggieling** [comment]
Anika,

After reading your earlier response and suggestion, I checked the column-width property and came to the same solution (in userall.css).  The only difference being the naming of the classes.  I used .wrap_colw10, .wrap_colw20 and .wrap_colw30.
colw to indicate that it is multicolumn based on definition of the width and the value indicating the actual width in em value.
Works like a charm.

Once your solution is released officially I will adjust the code in my pages and remove the manual adjustments in userall.css.

The only thing I do not see in your [files changed] tab is a definition to prevent page breaks in paragraphs in such a multicolumn environment

  .wrap_colw10 p, .wrap_colw20 p, .wrap_colw30 p {
    page-break-inside: avoid;
  }

I do not know if something similar is present in another related section of your stylesheet.  If not I will preserve this in userall.css

Thanks for the quick solution.



Gerben Gieling
IP Specialist

Synthon BV
Microweg 22 | P.O. Box 7071 | 6503 GN  Nijmegen | The Netherlands
T: +31(0)24 37 27 700 | F: +31(0)24 37 27 705 | www.synthon.com<http://www.synthon.com>

**Comment by selfthinker** [comment]
I tried `page-break-inside: avoid;` but don't think it fits well to a couple of use cases.

There is also the 'nopagebreak' wrap class, but that is currently only used in the print stylesheet. I wonder if it makes sense to move that to be used in all stylesheets.
