### ISSUE TITLE
wrap + page include = not work

### ISSUE THREAD

**Issue by sdamo** [selfthinker/dokuwiki_plugin_wrap#160]
This syntax does not work:

```
<WRAP group>
<WRAP half column>
{{page>article:article1}}
</WRAP>

<WRAP half column>
{{page>article:article2}}
</WRAP>
</WRAP>
```

Content **article:article1**:

```
====== article1 ======

  * [[article:page1]]
  * [[article:page2]]
  * [[article:page3]]
```

Content **article:article2**:

```
====== article2 ======

  * [[article:page4]]
  * [[article:page5]]
  * [[article:page6]]
```

**Comment by selfthinker** [comment]
The Include plugin automatically closes the section before it is included. That is intentional. But you can overwrite that by using the `inline` flag, e.g.
```
{{page>article:article1&inline}}
```
As found on https://www.dokuwiki.org/plugin:include#the_include_plugin_breaks_the_wrap_and_folded_and_similar_plugins_when_used_inside_them
