### ISSUE TITLE
Wrong release date in plugin webpage

### ISSUE THREAD

**Issue by jzaers** [selfthinker/dokuwiki_plugin_wrap#177]
Last updated on 2018-08-22

should read 

Last updated on 2018-04-22

This leads to unwanted update notifications in the extension manager. 

Thx for fixing. Cheers, Jo.

**Comment by mprins** [comment]
it's been fixed, but your wiki will keep telling there is a new version for the rest of the day

**Comment by selfthinker** [comment]
Thanks both for raising and fixing.
