### ISSUE TITLE
Request: option to place ‘next page‘ on the left site

### ISSUE THREAD

**Issue by ParoTheParrot** [selfthinker/dokuwiki_plugin_wrap#208]
I‘ld like to have an option to place the ‘next page’ on the left site instead of the right site under the table (lookup).
Why? → On small screens (mobile devices) and wide tables the ‘next page’ text is far on the right site and not visible without scrolling. You must scroll to skip to the next page.
This behaviour is inconvenient and some wiki users reported “missing entries”, but they didn’t saw the ‘next page’ option!
Any Idea / chance?

**Comment by Klap-in** [comment]
Where is 'next page' coming from? I do not see where it generated by the wrap plugin.

Please reopen with an example which I can use to reproduce the situation.
