### ISSUE TITLE
Undefined index $attr['lang']

### ISSUE THREAD

**Issue by bradbulger** [selfthinker/dokuwiki_plugin_wrap#211]
In the getAttributes() method of helper_plugin_wrap there's a test of $attr['lang']. It's not always defined, apparently. Changing that test to !empty() clears the warning.

-        if($attr['lang']) {
+        if (!empty($attr['lang'])) {

**Comment by bradbulger** [comment]
there are a number of other places in there that need the same kind of change. or else $attr needs to be initialized with default values for the expected keys.

**Comment by Klap-in** [comment]
Fixed
