### ISSUE TITLE
Warning: Use of undefined constant

### ISSUE THREAD

**Issue by bduplanty** [selfthinker/dokuwiki_plugin_wrap#216]
```
Warning: Use of undefined constant DOKU_LEXER_ENTER - assumed 'DOKU_LEXER_ENTER' (this will throw an Error in a future version of PHP) in /Users/bruce/Sites/home/lib/plugins/wrap/syntax/div.php on line 91

Warning: Use of undefined constant DOKU_LEXER_SPECIAL - assumed 'DOKU_LEXER_SPECIAL' (this will throw an Error in a future version of PHP) in /Users/bruce/Sites/home/lib/plugins/wrap/syntax/div.php on line 107

Warning: Use of undefined constant DOKU_LEXER_EXIT - assumed 'DOKU_LEXER_EXIT' (this will throw an Error in a future version of PHP) in /Users/bruce/Sites/home/lib/plugins/wrap/syntax/div.php on line 115

Warning: Use of undefined constant DOKU_LEXER_ENTER - assumed 'DOKU_LEXER_ENTER' (this will throw an Error in a future version of PHP) in /Users/bruce/Sites/home/lib/plugins/wrap/syntax/div.php on line 91

Warning: Use of undefined constant DOKU_LEXER_SPECIAL - assumed 'DOKU_LEXER_SPECIAL' (this will throw an Error in a future version of PHP) in /Users/bruce/Sites/home/lib/plugins/wrap/syntax/div.php on line 107

Warning: Use of undefined constant DOKU_LEXER_EXIT - assumed 'DOKU_LEXER_EXIT' (this will throw an Error in a future version of PHP) in /Users/bruce/Sites/home/lib/plugins/wrap/syntax/div.php on line 115
```

Using the latest release candidate of Dokuwiki - Release rc2-2020-06-01 "Hogfather" RC2
Using the latest release of the Wrap plugin

**Comment by NamelessRumia** [comment]
I don't know if this is the solution, but have you tried running [the File Cleanup plugin](https://www.dokuwiki.org/plugin:cleanup)?
That got rid of the warning messages and issue with columns not working for me.

**Comment by phy25** [comment]
Related to https://github.com/splitbrain/dokuwiki/issues/3146.

**Comment by eilko** [comment]
> I don't know if this is the solution, but have you tried running [the File Cleanup plugin](https://www.dokuwiki.org/plugin:cleanup)?
> That got rid of the warning messages and issue with columns not working for me.

I already started with an empty cache directory. didn't solve it for me.

**Comment by eilko** [comment]
> Related to [splitbrain/dokuwiki#3146](https://github.com/splitbrain/dokuwiki/issues/3146).

thanks, replacing my dokuwiki files with the current master branch files, solved the warning message and the problems with columns

**Comment by bduplanty** [comment]
That did it.  Thank you all for your suggestions as well as linking to the other reference!
