### ISSUE TITLE
No colums with "Hogfather"

### ISSUE THREAD

**Issue by eilko** [selfthinker/dokuwiki_plugin_wrap#217]
Using the latest release candidate of Dokuwiki - Release rc2-2020-06-01 "Hogfather" RC2
Using the latest release of the Wrap plugin
Using Edge Chromium, Safari, both on macOs

My home page uses wrap plugin to devide the text in two colums. With "Hogfather" this is shown as one colum. But when I run the page with the ?purge=yes option, it shows as two colums like before. 

How it looks in older versions and with ?purge=yes 
<img width="1123" alt="Screenshot 2020-06-05 at 15 40 03" src="https://user-images.githubusercontent.com/1078401/83883030-40cc4e00-a743-11ea-85aa-aed8b87059a6.png">

<img width="467" alt="Screenshot 2020-06-05 at 15 39 14" src="https://user-images.githubusercontent.com/1078401/83883099-56da0e80-a743-11ea-8f04-93ca9b3b8825.png">

and how it looks like after a refresh without the ?purge=yes option.

<img width="1045" alt="Screenshot 2020-06-05 at 15 39 47" src="https://user-images.githubusercontent.com/1078401/83883160-65c0c100-a743-11ea-819e-495ef2e4d4a0.png">

<img width="724" alt="Screenshot 2020-06-05 at 15 39 27" src="https://user-images.githubusercontent.com/1078401/83883176-6bb6a200-a743-11ea-9907-59c332405d35.png">

**Comment by konrag** [comment]
I'm also seeing this. I have pages included as sections into another page, and the section page looks like this on a clean load:

![good](https://user-images.githubusercontent.com/38045178/83910191-f5a04400-a71e-11ea-9989-ab09470cd400.png)

But on a reload, it turns into:

![broken](https://user-images.githubusercontent.com/38045178/83910220-0486f680-a71f-11ea-8788-e27d9ad6e6c5.png)

Using ?purge=true seems to fix it until it is cached again. I've tried setting `~~NOCACHE~~` on the pages in question but it doesn't seem to matter.

**Comment by eilko** [comment]
> Related to [splitbrain/dokuwiki#3146](https://github.com/splitbrain/dokuwiki/issues/3146).

Replacing my dokuwiki files with the current master branch files, solved the warning message and the problems with columns
