### ISSUE TITLE
<wrap></wrap> syntax breaks comments (/* It is a comment */)

### ISSUE THREAD

**Issue by Poukram35** [selfthinker/dokuwiki_plugin_wrap#227]
Hi,
happy new year! :-)
I think I found a little bug. I did several tests and obviously `<wrap></wrap>` syntax breaks comments (`/* It is a comment */`). It did not with Dokuwiki previous version.
The following syntax works : `<WRAP>  test  /*it is a test*/ </WRAP>`
We did not see the comment when the page is saved
But syntax with lowercase wrap breaks the comment syntax plugin : `<wrap>  test2  /*it is a another test*/ </wrap>`
When the page is saved, we can see :  `test2  /*it is a another test*/`
The comment is not hidden...

Thanks if you can fix this litlle bug :-)
Have a good day
Olivier

**Comment by erik-alm** [comment]
Interesting, I found [other issues](https://github.com/dokufreaks/plugin-comment/issues/14#issue-1224149210) but they were with the comment plugin, not the wrap plugin.

`<wrap> test /* test */ </wrap>`

Renders as expected. You need spaces, but apparently in more places than from my bug.

**Comment by Klap-in** [comment]
`/*    */` is syntax that is not part of this plugin.

If there are syntaxes that are recognized earlier then other syntaxes, it is an indication that the getSort value is lower. 
The wrap plugin uses a sort value of 195. 

The comment plugin uses sort value of 321. So of course the wrap plugins wins here. Probably it is most logical to change the sort value of the comment plugin.

(see also https://www.dokuwiki.org/devel:parser:getsort_list and https://www.dokuwiki.org/devel:syntax_plugins#sort_number)

Closed won't fix by wrap plugin.
