### ISSUE TITLE
// breaks <WRAP>...</WRAP>

### ISSUE THREAD

**Issue by surruk51** [selfthinker/dokuwiki_plugin_wrap#230]
This is a very useful plugin, but I just encountered a problem. I wanted to force a line break using // ( I realise it should be \\\\), but when I did the parser failed to see the \<\/WRAP\>. The code is as below. 

The Dokuwiki version is Release 2020-07-29 "Hogfather". The Wrap plugin was downloaded two days ago (2022-02-26). The server is running Apache 2.4.41 (Ubuntu) and PHP 7.4

     =====Test Page=====

    <WRAP>
    {{ balicwc:dog.png?300x300 }} //
    This JPEG file is a dog 
    </WRAP>
    
    <WRAP>
    {{ balicwc:2021-05-31-143902.webm  | }}
    webm file  
    </WRAP>

**Comment by surruk51** [comment]
![Screenshot from 2022-02-28 22-23-50](https://user-images.githubusercontent.com/3067699/156000265-5c049266-a6d0-4852-9b59-852b7faf0090.png)

**Comment by erik-alm** [comment]
That's not due to the WRAP-plugin. It's because you've added a half italics with the `//`. It's another DokuWiki syntax plugin half activated inside the WRAP plugin. You can see your text is italicized. Add an ending `//` and the WRAP should render just fine.

**Comment by Klap-in** [comment]
Changing `//` into `\\` fixes this issue.

```
 =====Test Page=====

<WRAP>
{{ balicwc:dog.png?300x300 }} \\
This JPEG file is a dog 
</WRAP>

<WRAP>
{{ balicwc:2021-05-31-143902.webm  | }}
webm file  
</WRAP>
```

**Comment by surruk51** [comment]
Thanks
