### ISSUE TITLE
Errors with Igor RC2 and PHP Version 8.1.6

### ISSUE THREAD

**Issue by saggi-dw** [selfthinker/dokuwiki_plugin_wrap#234]
On a test installation of Igor with xampp and PHP 8.1 I get the following errors:
```
Warning: Undefined array key "lang" in E:\xampp\htdocs\dokuwiki\lib\plugins\wrap\helper.php on line 94
Warning: Undefined array key "id" in E:\xampp\htdocs\dokuwiki\lib\plugins\wrap\helper.php on line 117
Warning: Undefined array key "dir" in E:\xampp\htdocs\dokuwiki\lib\plugins\wrap\helper.php on line 128
```
with the expression
```
<WRAP center round info 60%>
info box
</WRAP>
```
Also with others, like columns I get `Undefined array key` warnings.
If more information is needed I can provide it.

saggi

**Comment by LMS235** [comment]
Also on PHP 8.1

Got error 'width" in <xxx>/wiki/lib/plugins/wrap/helper.php on line 119

**Comment by syntaxseed** [comment]
Created a PR to fix this.
#237
