### ISSUE TITLE
bug wrap 2022-07-31 "Igor"

### ISSUE THREAD

**Issue by tuxmika** [selfthinker/dokuwiki_plugin_wrap#236]
Hello

I recently upgraded to version 2022-07-31 "Igor" with DokuWiki Upgrade Plugin and now when I log in and go to pages or use the wrap plugin I get error messages :

Warning: Undefined array key "lang" in /htdocs/wiki.mickaelbonnard.fr/lib/plugins/wrap/helper.php on line 94

Warning: Undefined array key "id" in /htdocs/wiki.mickaelbonnard.fr/lib/plugins/wrap/helper.php on line 117

Warning: Undefined array key "width" in /htdocs/wiki.mickaelbonnard.fr/lib/plugins/wrap/helper.php on line 119

Warning: Undefined array key "dir" in /htdocs/wiki.mickaelbonnard.fr/lib/plugins/wrap/helper.php on line 128

Warning: Undefined array key "hid" in /htdocs/wiki.mickaelbonnard.fr/inc/html.php on line 136

Warning: Undefined array key "hid" in /htdocs/wiki.mickaelbonnard.fr/inc/html.php on line 136

**Comment by syntaxseed** [comment]
Happens for me as well on PHP 8.1.

**Comment by syntaxseed** [comment]
Created a PR to fix this.
#237

**Comment by syntaxseed** [comment]
Second PR fixes last 2 errors.

#238

**Comment by Klap-in** [comment]
I cannot reproduce the messages here, maybe I have different log settings..
All warnings are now solved?
