### ISSUE TITLE
New Stable?

### ISSUE THREAD

**Issue by LMS235** [selfthinker/dokuwiki_plugin_wrap#239]
Hello,

the current "stable" is from 2018-04-22 and some improvements have been implemented since then. Many update their plugins only to the stable versions which are linked on dokuwiki.org. So at the latest with the latest IGOR and PHP8 fixes you should release a new stable. 

Regards

**Comment by Klap-in** [comment]
@selfthinker what is your policy here? Do you release a stable version?

**Comment by Klap-in** [comment]
I tried to update the stable tag. I hoped I succeed.

**Comment by LMS235** [comment]
i updated the dokuwiki.org description to the new stable date
