### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by dregad** [selfthinker/dokuwiki_plugin_wrap#262]
The last "official" release was in August 2022. With Jack Jackrum I'm getting drown in **a lot** of deprecation warnings for issues that have already been fixed.

It would be nice if you could cut a new release with those fixes.

Cheers.

**Comment by nerun** [comment]
Or dev could change download link in [DokuWiki](https://www.dokuwiki.org/plugin%3Awrap) 

from

https://github.com/selfthinker/dokuwiki_plugin_wrap/archive/stable.zip

to

https://github.com/selfthinker/dokuwiki_plugin_wrap/archive/refs/heads/master.zip

**Comment by fiwswe** [comment]
I think this could be closed now?
