### ISSUE TITLE
Incomplete release 2023-07-21

### ISSUE THREAD

**Issue by fiwswe** [selfthinker/dokuwiki_plugin_wrap#270]
The [Plugin page](https://dokuwiki.org/plugin:wrap) lists version 2023-07-21 and the Extension Manager offers this version as an update.

But updating actually loads version 2022-08-10. This leads to the Extension Manager immediately offering the same update again.

The reason is that the download link points to the stable branch and that branch has not been updated.

**Comment by Klap-in** [comment]
Ah, good point, reverted.

**Comment by fiwswe** [comment]
Ok, that's one way to solve the issue.

But I was hoping that either the download link could be adjusted and/or a new release tag created or that the stable tag could be updated to reflect the new version.

**Comment by Klap-in** [comment]
Sure, later I can create a release. I think I will remove the release step.
I do minimal maintenance here. I considered @selfthinker still as maintainer, therefore I would not like to pull over everything here. But unfortunately she seems not much active anymore here.

**Comment by Klap-in** [comment]
An update is released!
