### ISSUE TITLE
wrap column div closed by the include plugin

### ISSUE THREAD

**Issue by Klap-in** [selfthinker/dokuwiki_plugin_wrap#80]
When including a page the include plugin closes the div of the column too early.
At first glance, wrapping this included plugin (manually) with the div works fine.

I did not check code sofar. Maybe this should be an include plugin issue?

```
<WRAP group>
<WRAP half column>

{{page>werkgroepen_2013-2014#werkgroepen_2013-2014}}

</WRAP>

<WRAP half column>

==== Voorgaande werkgroepen ====
  * [[werkgroepen 2014-2015]]
  * [[werkgroepen 2013-2014]]
  * [[werkgroepen 2012-2013]]
  * [[werkgroepen 2011-2012]]
  * [[werkgroepen 2010-2011]]
  * [[werkgroepen 2009-2010]]
  * [[werkgroepen 2008-2009]]
 ...


</WRAP>
</WRAP>
```

**Comment by selfthinker** [comment]
This is intended behaviour of the include plugin. You can fix that by appending `&inline` to the include syntax.
See also https://www.dokuwiki.org/plugin:include#the_include_plugin_breaks_the_wrap_and_folded_and_similar_plugins_when_used_inside_them and https://www.dokuwiki.org/plugin:include#why_does_the_include_plugin_first_close_the_previous_section_and_opens_it_again_afterwards

From the `inline` flag description:
> Don't close/open sections when including a page. This flag should be used when the include syntax is used inside other syntax elements like lists or tables or inside other plugin syntax.
